load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "test_reverse_enumerate",
    size = "small",
    srcs = ["test_reverse_enumerate.py"],
    deps = [
        "//vinpytools:generator",
        "//vinpytools:iterator",
    ],
)
